### ISSUE TITLE
off-by-one error when passing events?

### ISSUE THREAD

**Issue by sebastianschmid** [jhonis/e-calendar#3]
d.getMonth gives a value between 0 and 11; it seems to me you're using them incorrectly.

I had an issue where all Dates passed via ISO-Date-String got off by one (e.g. displayed in May when they really were in June).

So, remove the (-1) next to d.getMonth() in Lines 125 and 140 and add (+1) on Line 141.

Sorry, I can't really provide you with a Testcase, but it seems to work now for me.

**Comment by jhonis** [comment]
Thank you by the sugestion Sebastian. I have made this changes in issue #4 and now it is correct.
