### ISSUE TITLE
Last day month Jumps to the next Months

### ISSUE THREAD

**Issue by carlosromanmena** [jhonis/e-calendar#4]
![sin titulo](https://cloud.githubusercontent.com/assets/16671957/12272989/e8c5d602-b928-11e5-8322-c0f0f310305f.png)

When try to apply a new date on an event like this: 
datetime: new Date(2016, 1, 31, 12, 30),
with format: Year(Actual), Month(January), Day...

Another events runs with any problem...
But this event with day 30 or 31, jumps into the next month: February, on the 1 or 2 day of February respectively.

**Comment by jhonis** [comment]
Issue fixed, but we need to use the correct datetime object with month starting from 0 to 11.
